/**
 * The published baseline as the first release (Phase 5C).
 *
 * The live site was built from snapshot/baseline.json before releases
 * existed. This records that snapshot as release 1 — status published,
 * origin baseline_import — so every later release has a published baseline
 * to be compared with, validated against and rolled back to.
 *
 * Pure: renders the one-off SQL from the snapshot text. It reads no files,
 * opens no connection and applies nothing. scripts/db/import-release-baseline.mjs
 * runs it, verifies it offline and saves it.
 *
 * The SQL checks, before writing anything, that the database really holds
 * this baseline as its published state: every document's published revision
 * equals the snapshot's content, every metric's first version (the import)
 * projects to the snapshot's metric, and the linked phrases match. Drafts
 * saved since then are left exactly as they are; they show up as unpublished
 * changes, and nothing is published by this import.
 */

/** Dollar-quote tags for the DO block and the embedded snapshot; the snapshot must contain neither. */
const BLOCK = '$release_baseline$';
const TAG = '$baseline_snapshot$';

export interface ReleaseBaselineSql {
  sql: string;
  expected: { metrics: number; documents: number; linkedPhrases: number };
}

interface BaselineShape {
  metrics: readonly unknown[];
  linkedPhrases: readonly unknown[];
  documents: Readonly<Record<string, unknown>>;
}

function countDocuments(documents: BaselineShape['documents']): number {
  return Object.values(documents).reduce<number>((total, entry) => {
    if (entry && typeof entry === 'object' && 'type' in entry) return total + 1;
    if (entry && typeof entry === 'object') return total + Object.keys(entry).length;
    return total;
  }, 0);
}

export function releaseBaselineSql(snapshotText: string): ReleaseBaselineSql {
  for (const tag of [BLOCK, TAG]) {
    if (snapshotText.includes(tag)) throw new Error(`the snapshot contains ${tag} and cannot be embedded`);
  }
  const snapshot = JSON.parse(snapshotText) as BaselineShape;
  const expected = {
    metrics: snapshot.metrics.length,
    documents: countDocuments(snapshot.documents),
    linkedPhrases: snapshot.linkedPhrases.length,
  };

  const sql = `-- =====================================================================
-- Published baseline release — generated by scripts/db/import-release-baseline.mjs
-- Source: snapshot/baseline.json
--   ${expected.metrics} metrics, ${expected.documents} documents, ${expected.linkedPhrases} linked phrases
--
-- Apply ONCE, by hand, as the database owner, after the Phase 5C migration
-- (20260924000100_release_publishing.sql), metrics_baseline.sql and
-- references_baseline.sql. This is not a migration and must not be applied
-- automatically.
--
-- Records the snapshot the live site is built from as release 1 (published,
-- origin baseline_import). It refuses to run unless public.releases is empty
-- and the database's published state equals this snapshot: every document's
-- published revision, every metric's first (imported) version and every
-- linked phrase. It changes no metric, document or draft: it only inserts the
-- release and links the baseline history rows (metric versions, document
-- revisions) to it. Any failure rolls the whole import back.
-- =====================================================================

begin;

do ${BLOCK}
declare
  v_snapshot constant jsonb := ${TAG}${snapshotText}${TAG}::jsonb;
  v_release_id bigint;
  v_problems text[];
  v_count integer;
begin
  if exists (select 1 from public.releases) then
    raise exception 'public.releases is not empty; the baseline release is imported once, before any release';
  end if;

  -- Documents: the published revision of each holds exactly the snapshot content.
  select count(*) into v_count from public.documents;
  if v_count <> ${expected.documents} then
    raise exception 'expected ${expected.documents} documents, found %', v_count;
  end if;
  v_problems := array(
    select s.doc_type || '/' || s.slug
      from private.snapshot_documents(v_snapshot) s
      left join public.documents d on d.doc_type::text = s.doc_type and d.slug = s.slug
      left join public.document_revisions r on r.id = d.published_revision_id
     where d.status is distinct from 'published' or r.content is distinct from (s.document -> 'content')
        or d.schema_version is distinct from (s.document ->> 'schemaVersion')::integer
  );
  if cardinality(v_problems) > 0 then
    raise exception 'published documents differ from the baseline: %', v_problems;
  end if;

  -- Metrics: the first version of each (the import) projects to the snapshot metric.
  select count(*) into v_count from public.metrics;
  if v_count <> ${expected.metrics} then
    raise exception 'expected ${expected.metrics} metrics, found %', v_count;
  end if;
  v_problems := array(
    select element.item ->> 'id'
      from jsonb_array_elements(v_snapshot -> 'metrics') as element(item)
      left join public.metrics m on m.metric_key = element.item ->> 'id'
      left join lateral (
        select v.new_row from public.metric_versions v where v.metric_id = m.id order by v.id limit 1
      ) as first_version on true
     where first_version.new_row is null
        or private.metric_projection(first_version.new_row) is distinct from element.item
  );
  if cardinality(v_problems) > 0 then
    raise exception 'imported metric versions differ from the baseline: %', v_problems;
  end if;

  -- Linked phrases: the same set.
  v_problems := array(
    select missing.item ->> 'phrase' from (
      select element.item from jsonb_array_elements(v_snapshot -> 'linkedPhrases') as element(item)
      except
      select jsonb_build_object('location', p.location, 'phrase', p.phrase, 'metricIds', to_jsonb(p.metric_keys), 'reason', p.reason)
        from public.linked_phrases p
    ) as missing(item)
  );
  select count(*) into v_count from public.linked_phrases;
  if cardinality(v_problems) > 0 or v_count <> ${expected.linkedPhrases} then
    raise exception 'linked phrases differ from the baseline (% expected, % found)', ${expected.linkedPhrases}, v_count;
  end if;

  insert into public.releases (kind, status, origin, summary, snapshot, snapshot_sha256, live_at, document_revisions)
  values (
    'publish', 'published', 'baseline_import',
    'Published baseline: the snapshot the live site was built from before releases existed (snapshot/baseline.json)',
    v_snapshot,
    private.snapshot_sha256(v_snapshot),
    now(),
    (select jsonb_object_agg(d.id::text, d.published_revision_id::text) from public.documents d)
  )
  returning id into v_release_id;

  -- Link the baseline history rows to the release that published them.
  update public.metric_versions v
     set release_id = v_release_id
   where v.release_id is null
     and v.id in (select min(first_row.id) from public.metric_versions first_row group by first_row.metric_id);
  update public.document_revisions r
     set release_id = v_release_id
   where r.release_id is null
     and r.id in (select d.published_revision_id from public.documents d);

  perform private.write_audit('release_baseline_imported', 'releases', v_release_id::text, null, null,
    jsonb_build_object('snapshot_sha256', private.snapshot_sha256(v_snapshot), 'metrics', ${expected.metrics},
                       'documents', ${expected.documents}, 'linked_phrases', ${expected.linkedPhrases}));
end
${BLOCK};

commit;
`;

  return { sql, expected };
}
